# Assign3: Non-Linear Dimensionality Reduction - KPCA

# Importing Dependancies

In [5]:
import numpy as np
import pandas as pd
import warnings
import copy
warnings.filterwarnings("ignore")

# Reading Dataset

In [7]:
# read data into dataframe
df = pd.read_csv("./OnlineNewsPopularity.csv") 

# Drop Unused Features

Ignore the following attributes for this assignment: 0-1, 4-6, 13-38, and 60 (counting from 0)

In [8]:
# drop unused features
vals = [0, 1, 4, 5, 6, 60]
for i in range(13, 39):
    vals.append(i)

df = df.drop(df.columns[vals], axis = 1)
df.head()

n_tokens_title   n_tokens_content   num_hrefs   num_self_hrefs   num_imgs  \
0             12.0              219.0         4.0              2.0        1.0   
1              9.0              255.0         3.0              1.0        1.0   
2              9.0              211.0         3.0              1.0        1.0   
3              9.0              531.0         9.0              0.0        1.0   
4             13.0             1072.0        19.0             19.0       20.0   

    num_videos   average_token_length   num_keywords    LDA_00    LDA_01  ...  \
0          0.0               4.680365            5.0  0.500331  0.378279  ...   
1          0.0               4.913725            4.0  0.799756  0.050047  ...   
2          0.0               4.393365            6.0  0.217792  0.033334  ...   
3          0.0               4.404896            7.0  0.028573  0.419300  ...   
4          0.0               4.682836            7.0  0.028633  0.028794  ...   

    avg_positive_polarity   min_positive_polarity   max_positive_polarity  \
0                0.378636                0.100000                     0.7   
1                0.286915                0.033333                     0.7   
2                0.495833                0.100000                     1.0   
3                0.385965                0.136364                     0.8   
4                0.411127                0.033333                     1.0   

    avg_negative_polarity   min_negative_polarity   max_negative_polarity  \
0               -0.350000                  -0.600               -0.200000   
1               -0.118750                  -0.125               -0.100000   
2               -0.466667                  -0.800               -0.133333   
3               -0.369697                  -0.600               -0.166667   
4               -0.220192                  -0.500               -0.050000   

    title_subjectivity   title_sentiment_polarity   abs_title_subjectivity  \
0             0.500000                  -0.187500                 0.000000   
1             0.000000                   0.000000                 0.500000   
2             0.000000                   0.000000                 0.500000   
3             0.000000                   0.000000                 0.500000   
4             0.454545                   0.136364                 0.045455   

    abs_title_sentiment_polarity  
0                       0.187500  
1                       0.000000  
2                       0.000000  
3                       0.000000  
4                       0.136364  

[5 rows x 29 columns]

# Drop Unused Data Points
 
We will only use the first 5000 data points

In [11]:
df = df.iloc[:5000]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 29 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0    n_tokens_title                5000 non-null   float64
 1    n_tokens_content              5000 non-null   float64
 2    num_hrefs                     5000 non-null   float64
 3    num_self_hrefs                5000 non-null   float64
 4    num_imgs                      5000 non-null   float64
 5    num_videos                    5000 non-null   float64
 6    average_token_length          5000 non-null   float64
 7    num_keywords                  5000 non-null   float64
 8    LDA_00                        5000 non-null   float64
 9    LDA_01                        5000 non-null   float64
 10   LDA_02                        5000 non-null   float64
 11   LDA_03                        5000 non-null   float64
 12   LDA_04                        5000 non-null   f

Based on the dataframe info, we now have 29 features remaining and the first 5000 points remaining. 

# Compute Kernel Matrix

**save data as numpy array**

In [13]:
data = df.to_numpy()
data[:5]

array([[ 1.20000000e+01,  2.19000000e+02,  4.00000000e+00,
         2.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         4.68036530e+00,  5.00000000e+00,  5.00331204e-01,
         3.78278930e-01,  4.00046751e-02,  4.12626477e-02,
         4.01225435e-02,  5.21617145e-01,  9.25619835e-02,
         4.56621005e-02,  1.36986301e-02,  7.69230769e-01,
         2.30769231e-01,  3.78636364e-01,  1.00000000e-01,
         7.00000000e-01, -3.50000000e-01, -6.00000000e-01,
        -2.00000000e-01,  5.00000000e-01, -1.87500000e-01,
         0.00000000e+00,  1.87500000e-01],
       [ 9.00000000e+00,  2.55000000e+02,  3.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         4.91372549e+00,  4.00000000e+00,  7.99755687e-01,
         5.00466754e-02,  5.00962518e-02,  5.01006734e-02,
         5.00007119e-02,  3.41245791e-01,  1.48947811e-01,
         4.31372549e-02,  1.56862745e-02,  7.33333333e-01,
         2.66666667e-01,  2.86914601e-01,  3.33333333e-02,
         7.00

In [14]:
print(data.shape)

(5000, 29)


**Compute Kernel Matrix** where each K(xi, xj) is = xi * xj

In [20]:
kernel = []
row = []
for i in range(len(data)):
    
    
    for j in range(len(data)):
        row.append(np.dot(data[i], data[j]))
    
    kernel.append(row)
    row = []

In [21]:
kernel = np.array(kernel)
print(kernel.shape)

(5000, 5000)


Now kernel is an nxn matrix made of dot products between data points

# Center Kernel Matrix

In [23]:
# get the nxn identity matrix
I = np.identity(len(kernel))

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [26]:
# get the ones matrix
ones = np.ones((len(kernel), len(kernel)))
ones

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])